version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: votingapp
      MYSQL_USER: votingapp
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
